# This file was adapted from https://github.com/dagger/dagger/blob/main/.golangci.yml
# to get a decent set of defaults.

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - copyloopvar
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-dirs:
    - cmd/eywagen/eywatest

linters-settings:
  revive:
    rules:
      # This rule is annoying. Often you want to name the
      # parameters for clarity because it conforms to an
      # interface.
      - name: unused-parameter
        severity: warning
        disabled: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
