// generated by eywa. DO NOT EDIT. Any changes will be overwritten.
package eywatest

import (
	"github.com/imperfect-fourth/eywa"
	"github.com/google/uuid"
	"bytes"
)


const testTable_Name eywa.FieldName[testTable] = "name"

func testTable_NameField(val string) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_Name,
		Value: val,
	}
}
const testTable_Age eywa.FieldName[testTable] = "age"

func testTable_AgeField(val *int) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_Age,
		Value: val,
	}
}
const testTable_ID eywa.FieldName[testTable] = "id"

func testTable_IDField(val uuid.UUID) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_ID,
		Value: val,
	}
}
const testTable_custom eywa.FieldName[testTable] = "custom"

func testTable_customField(val *customType) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_custom,
		Value: val,
	}
}

func testTable_testTable2(subField eywa.FieldName[testTable2], subFields ...eywa.FieldName[testTable2]) string {
	buf := bytes.NewBuffer([]byte("testTable2 {"))
	buf.WriteString(string(subField))
	for _, f := range subFields {
		buf.WriteString("\n")
		buf.WriteString(string(f))
	}
	buf.WriteString("}")
	return buf.String()
}

const testTable2_ID eywa.FieldName[testTable2] = "id"

func testTable2_IDField(val *uuid.UUID) eywa.Field[testTable2] {
	return eywa.Field[testTable2]{
		Name: testTable2_ID,
		Value: val,
	}
}
