// generated by eywa. DO NOT EDIT. Any changes will be overwritten.
package eywatest

import (
	"github.com/imperfect-fourth/eywa"
	"github.com/google/uuid"
)


const testTable_Name eywa.FieldName[testTable] = "name"

func testTable_NameField(val string) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_Name,
		Value: val,
	}
}
const testTable_Age eywa.FieldName[testTable] = "age"

func testTable_AgeField(val *int) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_Age,
		Value: val,
	}
}
const testTable_ID eywa.FieldName[testTable] = "id"

func testTable_IDField(val uuid.UUID) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_ID,
		Value: val,
	}
}
const testTable_custom eywa.FieldName[testTable] = "custom"

func testTable_customField(val *customType) eywa.Field[testTable] {
	return eywa.Field[testTable]{
		Name: testTable_custom,
		Value: val,
	}
}
